import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/compnents/Navbar";
import Banner from "./compnents/Banner";
import WorkOutsProvider from "@/Context/WorkOutsContext";
import { ToastContainer } from "react-toastify";
import Footer from "./compnents/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "FITLOG",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
       <WorkOutsProvider>
         <Navbar></Navbar>

        {children}
        <Footer></Footer>
       </WorkOutsProvider>
       <ToastContainer />
      </body>
    </html>
  );
}
